package com.peng.wechatmoment.bean.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.peng.wechatmoment.bean.dao.MomentsDAOBean;

import com.peng.wechatmoment.bean.dao.MomentsDAOBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig momentsDAOBeanDaoConfig;

    private final MomentsDAOBeanDao momentsDAOBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        momentsDAOBeanDaoConfig = daoConfigMap.get(MomentsDAOBeanDao.class).clone();
        momentsDAOBeanDaoConfig.initIdentityScope(type);

        momentsDAOBeanDao = new MomentsDAOBeanDao(momentsDAOBeanDaoConfig, this);

        registerDao(MomentsDAOBean.class, momentsDAOBeanDao);
    }
    
    public void clear() {
        momentsDAOBeanDaoConfig.clearIdentityScope();
    }

    public MomentsDAOBeanDao getMomentsDAOBeanDao() {
        return momentsDAOBeanDao;
    }

}
